"""empty message

Revision ID: 4ae906c011d5
Revises: 8271bbad6f40
Create Date: 2024-08-08 16:24:42.852994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae906c011d5'
down_revision = '8271bbad6f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
