"""empty message

Revision ID: 832448e9fcb6
Revises: 10bfad2e452f
Create Date: 2024-08-13 20:57:07.894572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832448e9fcb6'
down_revision = '10bfad2e452f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_lastname_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_lastname_key', ['lastname'])

    # ### end Alembic commands ###
