"""empty message

Revision ID: eb46510235b4
Revises: 832448e9fcb6
Create Date: 2024-08-14 15:22:23.425698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb46510235b4'
down_revision = '832448e9fcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('credit_card', 'paypal', 'cash', name='paymentmethods'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('credit_card', 'paypal', 'cash', name='paymentmethods'),
               nullable=False)

    # ### end Alembic commands ###
